### ISSUE TITLE
[CI] refactor doc-to-gh-page

### ISSUE THREAD

**Issue by GuillaumeDua** [GuillaumeDua/CppShelf#118]
- use actions/checkout@v4
- use spare-checkout

```yaml
- uses: actions/checkout@v4
  with:
    sparse-checkout: |
      .github
      src
```
