### ISSUE TITLE
[CI/docker] remote / ssh support

### ISSUE THREAD

**Issue by GuillaumeDua** [GuillaumeDua/CppShelf#197]
[UPDATE]

as a multi-stage image:

```yaml
FROM cpp-toolchain-dev as ssh-support
# etc.
```

---

part of #196 , but as a separated container

---

- SSH remote connection
- vscode remote developpement (ssh, rsync)
- remote debug

---

- shared network with the cpp-toolchain container ?

```yaml
version: '3'
services:
  container1:
    image: sshtest
    build: .
    networks:
      - sshtest
    ports:
      - 2201:22
 
  container2:
    image: sshtest
    build: .
    networks:
      - sshtest
    ports:
      - 2202:22
 
networks:
  sshtest:
```
