### ISSUE TITLE
[CI] multi-stage CI

### ISSUE THREAD

**Issue by GuillaumeDua** [GuillaumeDua/CppShelf#226]
```yml
jobs:
  ubuntu-latest-build:
    uses: ./.github/workflows/some_workflow.yml
    with:
      os: ubuntu-latest
```
